name: Deploy Sync Streams

on:
  push:
    branches:
      - main
    paths:
      - "sync_streams.yaml"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: node/.nvmrc

      - name: Install PowerSync CLI
        run: npm install powersync-ja/temp-cli

      - name: Deploy sync config
        env:
          PS_ADMIN_TOKEN: ${{ secrets.POWERSYNC_AUTH_TOKEN }}
          INSTANCE_ID: ${{ secrets.POWERSYNC_INSTANCE_ID }}
          PROJECT_ID: ${{ secrets.POWERSYNC_PROJECT_ID }}
          ORG_ID: ${{ secrets.POWERSYNC_ORG_ID }}
        run: |
          npx powersync deploy sync-config --directory=.

